### PR TITLE
Add Meteor 3.0 Compatibility 

### PR DESCRIPTION
**Pull request by harryadel**
Add 3.0-beta.0 to versionsFrom @afrokick Please merge and release

### CODE REVIEW

**Comment by afrokick** [comment]
Thanks @harryadel 

@Pavel-R Could you please release it?

**Review by Pavel-R — APPROVED** [review]

**Comment by harryadel** [comment]
Please publish a new version to atmosphere.

**Comment by afrokick** [comment]
Thanks @Pavel-R 

@harryadel  Now its done! https://atmospherejs.com/itgenio/persistent-session

**Comment by harryadel** [comment]
Thank you guys @afrokick @Pavel-R

**Comment by a4xrbj1** [comment]
@afrokick @Pavel-R - we have pull requests waiting to get your package ready for Meteor 3.x. Could you please take a look and action on it?

Thanks in advance

**Pull request merged**
